### ISSUE TITLE
Spritesheet outputting filenames with period (.)

### ISSUE THREAD

**Issue by sethjeffery** [nicholasstephan/grunt-spritesheet#7]
Since I updated grunt-spritesheet it no longer builds successfully because the outputted CSS is incorrectly named.

``` css
.sprite.-list-alltopics3. {
  background-image: url(../img/sprite.png);
  width: 16px;
  height: 16px;
  background-position: -636px -252px;
  display: inline-block;
  vertical-align: top;
}
```

I believe this stems from the following change: https://github.com/nicholasstephan/grunt-spritesheet/commit/cedfcded434df73fd52c971c336235dcde42a8e0#diff-097852fa3de0fb2185d7063e96272546R86

Previously you were hardcoding the extension as `.png` but now you have added `slice(1)` to cut off the period, which is affecting the way it treats filenames.
